- name: "restart haproxy"
  service:
    name: "haproxy"
    state: restarted
    enabled: yes
  become: yes
- name: "restart keepalived"
  service:
    name: "keepalived"
    state: restarted
    enabled: yes
  become: yes
