- name: "[clean] kubeadm reset"
  shell: "kubeadm reset --force --cri-socket=/var/run/containerd/containerd.sock"
  become: yes
  when: clean_kube is defined
  ignore_errors: yes

- name: "[clean] ensure kubeadm is not present"
  become: yes
  apt:
    name: kubeadm
    state: absent
    update_cache: yes
  when: clean_kube is defined

- name: "[clean] ensure kubelet is not present"
  become: yes
  apt:
    name: kubelet
    state: absent
    update_cache: yes
  when: clean_kube is defined

- name: "[clean] ensure kubectl is not present"
  become: yes
  apt:
    name: kubectl
    state: absent
    update_cache: yes
  when: clean_kube is defined

- name: "[clean] clean cni directory"
  shell: rm -rf /etc/cni/net.d
  become: yes
  when: clean_kube is defined

- name: create key directory if not exists ..
  become: yes
  file:
    path: /etc/apt/keyrings
    state: directory
  when: clean_kube is defined

- name: Adding kubernetes key ..
  become: yes
  apt_key:
    url:  https://packages.cloud.google.com/apt/doc/apt-key.gpg
    keyring: /etc/apt/keyrings/kubernetes-archive-keyring.gpg
    state: present
  when: clean_kube is defined

- name: Adding kubernetes repo ...
  become: yes
  apt_repository:
    repo: deb [signed-by=/etc/apt/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: kubernetes.list
  when: clean_kube is defined

- name: "apt update"
  apt:
    update_cache: yes
  become: yes
  when: clean_kube is defined

- name: install kubeadm
  become: yes
  apt:
    name: kubeadm={{ kube_version }}
    state: present
    update_cache: yes
    allow_downgrade: true
  when: clean_kube is defined

- name: install kubelet
  become: yes
  apt:
    name: kubelet={{ kube_version }}
    state: present
    update_cache: yes
    allow_downgrade: true
  when: clean_kube is defined

- name: install kubectl
  become: yes
  apt:
    name: kubectl={{ kube_version }}
    state: present
    update_cache: yes
    allow_downgrade: true
  when: clean_kube is defined
